package io.praecepta.rules.model.filter;

/**
 * 
 * @author rajasrikar
 *
 */
public enum ConditionOperatorType {

	EQUAL_CHARS, NOT_EQUAL_CHARS, EMPTY, NOT_EMPTY, LESS_THAN_NUMBER, GREATER_THAN_NUMBER, EQUAL_NUMBER, 
	NOT_EQUAL_NUMBER,GREATER_THAN_EQUAL_NUMBER,LESS_THAN_EQUAL_NUMBER,
	LESS_THAN_DATE,LESS_THAN_EQUAL_DATE, GREATER_THAN_DATE, GREATER_THAN_EQUAL_DATE,EQUAL_DATE, BETWEEN_DATE, CONTAINS_IN_COLLECTION, 
	NOT_CONTAINS_IN_COLLECTION, 
	MATCHING_COLLECTION, NOT_MATCHING_COLLECTION,BETWEEN,NOT_BETWEEN,LIKE,NOT_LIKE,STARTS_WITH,
	NOT_STARTS_WITH,ENDS_WITH,NOT_ENDS_WITH,
}
