package io.praecepta.rules.actions.enums;

// Change the name to PraeceptaFactorActionType
public enum PraeceptaFactorActionType {
	
	ADDITION, MULTIPLICATION, DIVISION, SUBTRACTION, DAYS_ADDITION, DAYS_SUBTRACTION,MINUTES_ADDITION,MINUTES_SUBTRACTION,
	HOURS_ADDITION,HOURS_SUBTRACTION,MONTHS_ADDDITION,MONTHS_SUBTRACTION,YEARS_ADDITION,YEARS_SUBTRACTION, CONCATENATION

}
