package io.praecepta.parser.execution.enums;

public enum PARSER_REQUEST_KEYS {
	RULE_GROUP_NAME, VERSION, RULES,SPACE_NAME,CLIENT_NAME,APP_NAME,PRE_RULE_GRP_SIDECARS,POST_RULE_GRP_SIDECARS,RULE_LEVEL_SIDECARS;
}
