package io.praecepta.parser.execution.enums;

public enum PARSER_REQUEST_TYPE {
	INSERT_RULE_SPACE,
	INSERT_RULE_GROUP,
	INSERT_MULTI_RULE_GROUP,
	UPDATE_MULTI_RULE_GROUP,
	INSERT_MULTI_NESTED_RULE_GROUP,
	UPDATE_MULTI_NESTED_RULE_GROUP,
	SELECT,
	EXECUTE_RULES,
	INSERT_SIDE_CARS,
	UPDATE_RULE_SPACE,
	UPDATE_RULE_GROUP,
	UPDATE_SIDE_CARS,
	DELETE_RULE_SPACE,
	DELETE_RULE_GROUP,
	DELETE_SIDE_CARS;
}
