package io.praecepta.dao.elastic.enums;

public enum AUDIT_ELEMENT_TYPE {
	VALUE_CHNAGE, CONDITION_OPERATOR_CHANGE, JOIN_OPERATOR_CHANGE, MATA_DATA_CHANGE,ACTION_STRATEGY_CHANGE,NEXT_CONDITION_JOIN_OPERATOR_CHANGE;
}
