package io.praecepta.dao.elastic.enums;

public enum AUDIT_ELEMENT_TYPE {
	VALUE_CHANGE, CONDITION_OPERATOR_CHANGE, JOIN_OPERATOR_CHANGE, META_DATA_CHANGE,ACTION_STRATEGY_CHANGE,SOURCE_ATTRIBUTE_CHANGE;
}
