package io.praecepta.rules.actions.enums;

public enum PraeceptaActionStrategyType {
	
	ADD_TO_PAYLOAD,
	ADD_TO_PAYLOAD_FROM_PAYLOAD,
	ADD_TO_PAYLOAD_FROM_CONSTANT,
	ADD_TO_HEADER,
	ADD_TO_HEADER_FROM_PAYLOAD,
	ADD_TO_HEADER_FROM_CONSTANT,
	/*SEND_MESSAGE_TO_KAFKA,
	SEND_MESSAGE_TO_AMQ,
	SEND_MESSAGE_TO_WMQ,
	INVOKE_REST_API_CALL,
	SEND_MESSAGE_TO_DB;*/

}
